# Refer to https://payu.readthedocs.io/en/latest/config.html for full details of the 
# payu configuration settings.

# PBS configuration

# If submitting to a different project to your default, uncomment line below
# and replace PROJECT_CODE with appropriate code. This may require setting shortpath
# project: PROJECT_CODE

# Force payu to always find, and save, files in this scratch project directory
# shortpath: /scratch/PROJECT_CODE

# Note: if laboratory is relative path, it is relative to shortpath/$USER
laboratory: access-esm

jobname: pre-industrial
queue: normal
walltime: 2:30:00


# Model configuration
model: access

submodels:
    - name: atmosphere
      model: um
      ncpus: 192
      exe: um_hg3.exe
      input:
        - /g/data/access/payu/access-esm/input/pre-industrial/atmosphere

    - name: ocean
      model: mom
      ncpus: 180
      exe: fms_ACCESS-CM.x
      input:
        - /g/data/access/payu/access-esm/input/pre-industrial/ocean/common
        - /g/data/access/payu/access-esm/input/pre-industrial/ocean/pre-industrial

    - name: ice
      model: cice
      ncpus: 12
      exe: cice_access_360x300_12x1_12p.exe
      input:
        - /g/data/access/payu/access-esm/input/pre-industrial/ice

    - name: coupler
      model: oasis
      ncpus: 0
      input:
        - /g/data/access/payu/access-esm/input/pre-industrial/coupler

# Collation
collate:
    exe: mppnccombine.spack
    restart: true
    mem: 4GB
    walltime: 1:00:00

restart: /g/data/vk83/experiments/inputs/access-esm1p5/modern/pre-industrial/restart/

# Modules for loading model executables
modules:
  use:
      - /g/data/vk83/modules/access-models/
  load:
      - access-esm1p5/2024.05.0


# Timing controls
calendar:
    start:
        year: 101
        month: 1
        days: 1

    runtime:
        years: 1
        months: 0
        days: 0

runspersub: 1

# Misc
restart_freq: 5

runlog: true
manifest:
  reproduce:
    exe: True
    
# set number of cores per node (28 for normalbw, 48 for normal on gadi)
platform:
    nodesize: 48

stacksize: unlimited
qsub_flags: -W umask=027


# Sync options for automatically copying data from ephemeral scratch space to 
# longer term storage
sync:
    enable: False # set path below and change to true
    path: null # Set to location on /g/data or a remote server and path (rsync syntax)

# If a postscript included (such as the automated netcdf conversion), the latest output and restart files will not 
# be automatically synced at the end of a run. To sync the latest output after a postscript has completed,
#  manually run `payu sync` from the command line.

# userscripts:

# postscript: