format: yamanifest
version: 1.0
---
work/atmosphere/INPUT/BC_hi_1850_ESM1.anc:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/modern/pre-industrial/atmosphere/aerosol/global.N96/2020.05.19/BC_hi_1850_ESM1.anc
  hashes:
    binhash: 8c9b22313e991592bb684c3395926c80
    md5: 74803eb36a358f9ac8ecdae36cdb7f56
work/atmosphere/INPUT/Bio_1850_ESM1.anc:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/modern/pre-industrial/atmosphere/aerosol/global.N96/2020.05.19/Bio_1850_ESM1.anc
  hashes:
    binhash: 436a287e78437b62498457a78d93211c
    md5: 69dc6afb4bc7524d346f3b82f2657c97
work/atmosphere/INPUT/DMS_conc.N96:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/modern/share/atmosphere/aerosol/global.N96/2020.05.19/DMS_conc.N96
  hashes:
    binhash: cbf986b9291704eb6ca48fb85cc309e9
    md5: 7e8ec8de832c0b9b8c1d9f0eda4d54e5
work/atmosphere/INPUT/Ndep_1850_ESM1.anc:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/modern/pre-industrial/atmosphere/land/biogeochemistry/global.N96/2020.05.19/Ndep_1850_ESM1.anc
  hashes:
    binhash: 97a1fe836679853405009550a3b3f90c
    md5: 48462cfa1aeed200c3b8d0bf1b49654a
work/atmosphere/INPUT/OCFF_1850_ESM1.anc:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/modern/pre-industrial/atmosphere/aerosol/global.N96/2020.05.19/OCFF_1850_ESM1.anc
  hashes:
    binhash: 8a358c0fca6c9dc7aa49586f504cf524
    md5: 95eec04860fa30ee863d30e67e683407
work/atmosphere/INPUT/STASHmaster/STASHmaster_A:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/STASHmaster/STASHmaster_A
  hashes:
    binhash: 813b5a254f5666450760da386ef43db4
    md5: 74cbbb76edfbd9f7c4b928609c00cd64
work/atmosphere/INPUT/STASHmaster/STASHmaster_A.original:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/STASHmaster/STASHmaster_A.original
  hashes:
    binhash: 8afe63c1aacc00f778c69872516c96c9
    md5: ed1004d9aca8d29baba143ea12defbb7
work/atmosphere/INPUT/STASHmaster/STASHmaster_O:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/STASHmaster/STASHmaster_O
  hashes:
    binhash: c644fb6c73afdf5eefd0e0086976d44b
    md5: 5a65d77c62d55e3b62e35ad9662d32a9
work/atmosphere/INPUT/STASHmaster/STASHmaster_S:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/STASHmaster/STASHmaster_S
  hashes:
    binhash: 241ae9a0dce937389f133d383024aaac
    md5: 85ff5d563968cf24d1be595b05b4e52d
work/atmosphere/INPUT/STASHmaster/STASHmaster_W:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/STASHmaster/STASHmaster_W
  hashes:
    binhash: f00ee794e8453bb6e386ac36a04ca757
    md5: 1e4391ea1f6234b33c33168bd7089d06
work/atmosphere/INPUT/STASHmaster/STASHsections_A:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/STASHmaster/STASHsections_A
  hashes:
    binhash: 2f4b6af4ec50f1bea692ecbc0f935bc9
    md5: 8525fd107dbea6184db74089f1d55fd9
work/atmosphere/INPUT/biogenic_351sm.N96L38:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/modern/share/atmosphere/aerosol/global.N96/2020.05.19/biogenic_351sm.N96L38
  hashes:
    binhash: 4016048ec8e26e6f84a868c1161e59a3
    md5: 55eb75f602a4639fb3c8ff40e36eb661
work/atmosphere/INPUT/cable_vegfunc_N96.anc:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/modern/share/atmosphere/land/vegetation/global.N96/2020.05.19/cable_vegfunc_N96.anc
  hashes:
    binhash: 4df1a198560578ae763526c730158cfd
    md5: 7a8cb16191ad29b081514657893530c6
work/atmosphere/INPUT/def_soil_params.txt:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/share/atmosphere/land/biogeophysics/resolution_independent/2020.05.19/def_soil_params.txt
  hashes:
    binhash: cde42a0c3d2324eb21bcf03b25d1201d
    md5: 93107e8c37e04ccf97471fd2ac8f63eb
work/atmosphere/INPUT/def_veg_params.txt:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/share/atmosphere/land/biogeophysics/resolution_independent/2020.05.19/def_veg_params.txt
  hashes:
    binhash: b4b2451b7f18d24e39749388a77180aa
    md5: 1f9a27f0e252bf6c466100573c126789
work/atmosphere/INPUT/modis_phenology_csiro.txt:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/share/atmosphere/land/biogeochemistry/resolution_independent/2020.05.19/modis_phenology_csiro.txt
  hashes:
    binhash: f519783ccfc63db8f88a82e6ca9f0a27
    md5: a7b89d25cff82cf13cf812a98ad3a029
work/atmosphere/INPUT/ozone_1850_ESM1.anc:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/modern/pre-industrial/atmosphere/forcing/global.N96/2020.05.19/ozone_1850_ESM1.anc
  hashes:
    binhash: 33522e53c88a05d43aa891f172b289c7
    md5: a64a01e3b092085fca308524a75a1cee
work/atmosphere/INPUT/pftlookup_csiro_v16_17tiles_wtlnds.csv:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/share/atmosphere/land/biogeochemistry/resolution_independent/2020.05.19/pftlookup_csiro_v16_17tiles_wtlnds.csv
  hashes:
    binhash: 1e98e47a305625ece80283331f01b863
    md5: 109d0702afd2cb0a66bf141faccaee30
work/atmosphere/INPUT/qrparm.mask:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/modern/share/atmosphere/grids/global.N96/2020.05.19/qrparm.mask
  hashes:
    binhash: d2d38fcb1eebdb0b419fcb2249075c23
    md5: f497c7827bd22ef0b98f1d1af776866d
work/atmosphere/INPUT/qrparm.soil_igbp_vg:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/modern/share/atmosphere/land/soiltype/global.N96/2020.05.19/qrparm.soil_igbp_vg
  hashes:
    binhash: deb56e757c2f4e4b84cef33dd7d2b23a
    md5: 26ce57f462dd574fe49f290ab7877112
work/atmosphere/INPUT/scycl_1850_ESM1_v4.anc:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/modern/pre-industrial/atmosphere/aerosol/global.N96/2020.05.19/scycl_1850_ESM1_v4.anc
  hashes:
    binhash: 7236ee314d8f707ce8d6f7292e12393d
    md5: 2c390f44c4f57078340cfbd408fdc754
work/atmosphere/INPUT/spec3a_lw_hadgem1_6on:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/share/atmosphere/spectral/resolution_independent/2020.05.19/spec3a_lw_hadgem1_6on
  hashes:
    binhash: 452161a3f5a54223fd593fb998aa5c59
    md5: 9ff85916dbb36ba6679b954d16387aee
work/atmosphere/INPUT/spec3a_sw_hadgem1_6on:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/share/atmosphere/spectral/resolution_independent/2020.05.19/spec3a_sw_hadgem1_6on
  hashes:
    binhash: b11add15022f62b14afbd36de8a5d81f
    md5: 0e74c13cf3333132f38d8c5c52e1c7eb
work/atmosphere/INPUT/stasets/X01001218:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/stasets/X01001218
  hashes:
    binhash: ed688987bfeb737222589f3f4359f2f1
    md5: 7293caa27798d235bd5520eede9700fb
work/atmosphere/INPUT/stasets/X01002207:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/stasets/X01002207
  hashes:
    binhash: 0d63fef5e7f439a04f232c71328d0db7
    md5: 448daeebba685950d0c347d0493b5fc4
work/atmosphere/INPUT/stasets/X01003236:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/stasets/X01003236
  hashes:
    binhash: 59866396fdc710bce6bbeedfae3a49ca
    md5: 71a2288ee0a7d0fc89dafe95653c128a
work/atmosphere/INPUT/stasets/X01003237:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/stasets/X01003237
  hashes:
    binhash: 2abd1d19974787fbd9404ccfec4062c1
    md5: 4efd39ac9a917525bbc35146d6770e3b
work/atmosphere/INPUT/stasets/X01003254:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/stasets/X01003254
  hashes:
    binhash: 9cb711f2d6f22b52c915a383f9bf675e
    md5: 1b5f7755f752c2ee2086ac6eba886ca3
work/atmosphere/INPUT/stasets/X01003255:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/stasets/X01003255
  hashes:
    binhash: 35a005ca3e1c3ea88968d7e7d650e9ee
    md5: f23a78b048f0cb52ed0e2beb57f00fa8
work/atmosphere/INPUT/stasets/X01003274:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/stasets/X01003274
  hashes:
    binhash: c2aa7644544dec51efbf4194a3026557
    md5: 032190f23c926eb47199da6e1f054bf1
work/atmosphere/INPUT/stasets/X01003275:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/stasets/X01003275
  hashes:
    binhash: 544af1e8e4f2f708e918cc7421422943
    md5: 120694f3d078b9ade033b56217e9ed85
work/atmosphere/INPUT/stasets/X01003276:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/stasets/X01003276
  hashes:
    binhash: a8c416736c912739dfbb0cc306d09156
    md5: 61afb6eb4e76efb2171c56d02742e9ad
work/atmosphere/INPUT/stasets/X01003277:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/stasets/X01003277
  hashes:
    binhash: d5d4ff715e406e2750fe55df1d45061b
    md5: d8cced93214dd8e84c0c9d06259412ab
work/atmosphere/INPUT/stasets/X01003278:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/stasets/X01003278
  hashes:
    binhash: 33f7c4974f5803841d3f178757bc2543
    md5: 032190f23c926eb47199da6e1f054bf1
work/atmosphere/INPUT/stasets/X01003279:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/stasets/X01003279
  hashes:
    binhash: 05f597a9dde6264059dd1c1f049869c1
    md5: 120694f3d078b9ade033b56217e9ed85
work/atmosphere/INPUT/stasets/X01003280:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/stasets/X01003280
  hashes:
    binhash: c1b894221e36b1787100c0b05a4f7eef
    md5: 61afb6eb4e76efb2171c56d02742e9ad
work/atmosphere/INPUT/stasets/X01003281:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/stasets/X01003281
  hashes:
    binhash: c484fe2e43beaff653a99b08d5b24a49
    md5: d8cced93214dd8e84c0c9d06259412ab
work/atmosphere/INPUT/stasets/X01003286:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/stasets/X01003286
  hashes:
    binhash: febe4d4416b0593a02dc87cfc88b150a
    md5: 062ab130605e4771a89b2a300a6154bf
work/atmosphere/INPUT/stasets/X01005207:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/stasets/X01005207
  hashes:
    binhash: ffbd233c57d1eaa191e8b36f0cc7a3c2
    md5: 3d1ccb47257c379b909e8d6098ab95a0
work/atmosphere/INPUT/stasets/X01005208:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/stasets/X01005208
  hashes:
    binhash: 9dc09e05d369c3af54c5fad4e22c7ab3
    md5: 8685052394200b839f115a667e7890ff
work/atmosphere/INPUT/stasets/X01005222:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/stasets/X01005222
  hashes:
    binhash: 673ae4983cfac79f7c499fca140bc8b2
    md5: 3edd8e46166dbed4102c329991a7a497
work/atmosphere/INPUT/stasets/X01005223:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/stasets/X01005223
  hashes:
    binhash: a109b98228c058253bf5b80b6c9ddbf9
    md5: 4633fea316272fd71cd823881d100c14
work/atmosphere/INPUT/stasets/X01010206:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/stasets/X01010206
  hashes:
    binhash: 368e441eec8c5a1ff0555c255eea6afe
    md5: 7d5e82e70a2f3936743eb957462d41aa
work/atmosphere/INPUT/sulpc_oxidants_N96_L38:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/modern/share/atmosphere/aerosol/global.N96/2020.05.19/sulpc_oxidants_N96_L38
  hashes:
    binhash: 0bb61cf0a1d470fb5798688580284d0b
    md5: 7c42d1faf74b2b9f6819f2349a8d0d25
work/atmosphere/INPUT/vertlevs_G3:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/share/atmosphere/grids/resolution_independent/2020.05.19/vertlevs_G3
  hashes:
    binhash: 89f1d61fecb388a00636c827d97648c7
    md5: 58ca02de69b16bd59771c81e06c4c21a
work/atmosphere/INPUT/volcts_18502000ave.dat:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/modern/pre-industrial/atmosphere/forcing/resolution_independent/2020.05.19/volcts_18502000ave.dat
  hashes:
    binhash: e1c3f66fdb65250bc58c8139a52b29e6
    md5: 47bd369c750be55d706ab60c78bc7aee
work/coupler/areas.nc:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/modern/share/coupler/grids/global.oi_1deg.a_N96/2020.05.19/areas.nc
  hashes:
    binhash: 70548e6301fa3280ea4a1daa517f3372
    md5: 1aac9e2f82d96176f7b87ba1efc8784e
work/coupler/grids.nc:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/modern/share/coupler/grids/global.oi_1deg.a_N96/2020.05.19/grids.nc
  hashes:
    binhash: d420eafedc3b15015501043aacae0d0a
    md5: 2348de62f5fe4d55ec849f79e5d027fd
work/coupler/masks.nc:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/modern/share/coupler/grids/global.oi_1deg.a_N96/2020.05.19/masks.nc
  hashes:
    binhash: 433ccede4284c6511911ef0e26b16702
    md5: 0a12503901fd3d595bc25b5d3008f9d3
work/coupler/rmp_cice_to_um1t_CONSERV_FRACNNEI.nc:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/modern/share/coupler/remapping_weights/global.oi_1deg.a_N96/2020.05.19/rmp_cice_to_um1t_CONSERV_FRACNNEI.nc
  hashes:
    binhash: 3da2f284e9e28a23f91708d0b10eadc5
    md5: a8129dba5b3a7f70a5bc2fbf7f0e4f68
work/coupler/rmp_cice_to_um1u_CONSERV_FRACNNEI.nc:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/modern/share/coupler/remapping_weights/global.oi_1deg.a_N96/2020.05.19/rmp_cice_to_um1u_CONSERV_FRACNNEI.nc
  hashes:
    binhash: 9bf9e5e77d72f26aec86e877db4249d3
    md5: 6fc856e7c2014e20903a01cdd61f4f2c
work/coupler/rmp_cice_to_um1v_CONSERV_FRACNNEI.nc:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/modern/share/coupler/remapping_weights/global.oi_1deg.a_N96/2020.05.19/rmp_cice_to_um1v_CONSERV_FRACNNEI.nc
  hashes:
    binhash: 6778c0da4c8792e6e724d34c7b88acab
    md5: a2a7d940a9eaab59ec8fa49154116a64
work/coupler/rmp_um1t_to_cice_CONSERV_DESTAREA.nc:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/modern/share/coupler/remapping_weights/global.oi_1deg.a_N96/2020.05.19/rmp_um1t_to_cice_CONSERV_DESTAREA.nc
  hashes:
    binhash: cab31779c0dfc56f3d135604c5d29e03
    md5: 25be6489585df07097d4b6009bf23ec2
work/coupler/rmp_um1t_to_cice_CONSERV_FRACNNEI.nc:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/modern/share/coupler/remapping_weights/global.oi_1deg.a_N96/2020.05.19/rmp_um1t_to_cice_CONSERV_FRACNNEI.nc
  hashes:
    binhash: 126ae5f0466b3359b9e6245b6ed50878
    md5: 269086623444b48d0cd481e69d4bdc5f
work/coupler/rmp_um1u_to_cice_CONSERV_FRACNNEI.nc:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/modern/share/coupler/remapping_weights/global.oi_1deg.a_N96/2020.05.19/rmp_um1u_to_cice_CONSERV_FRACNNEI.nc
  hashes:
    binhash: 7304e31fc9cadbaaec46bd2d880a2552
    md5: 58ea836bf1e12d5fc21460763b02548f
work/coupler/rmp_um1v_to_cice_CONSERV_FRACNNEI.nc:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/modern/share/coupler/remapping_weights/global.oi_1deg.a_N96/2020.05.19/rmp_um1v_to_cice_CONSERV_FRACNNEI.nc
  hashes:
    binhash: a055350241d10200eab15ac4d1474b2d
    md5: 3bf9569f34b657f2ecab8ef5c93e7659
work/ice/INPUT/grid.nc:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/modern/share/ice/grids/global.1deg/2020.05.19/grid.nc
  hashes:
    binhash: 610e9f5abc0583bfe67058e5ba4a1090
    md5: 1213e346055ee073fe33dc12578d99c6
work/ice/INPUT/kmt.nc:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/modern/share/ice/grids/global.1deg/2020.05.19/kmt.nc
  hashes:
    binhash: e7c97a616d26529d02550365a70d3f10
    md5: 2bde88b9e44c46aecf2ba2dff188d1ac
work/ice/INPUT/monthly_sstsss.nc:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/modern/share/ice/climatology/global.1deg/2020.05.19/monthly_sstsss.nc
  hashes:
    binhash: 2912bf96b404bbc258b0ac29f93dc2e5
    md5: 323d4c605f83f4d7d3126da70153c2ed
work/ocean/INPUT/bgc_param.nc:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/share/ocean/biogeochemistry/global.1deg/2024.07.12/bgc_param.nc
  hashes:
    binhash: 7d37cd5fa7d997e660efd6d9cf65f8b1
    md5: 9defb35e7a7181e9170a6ae57a4d3348
work/ocean/INPUT/dust.nc:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/modern/share/ocean/biogeochemistry/global.1deg/2020.05.19/dust.nc
  hashes:
    binhash: 26bc2f5ce1efaec22b61c7e5436b5a3e
    md5: bfbbea8ac46a932d0ec8631afbfc2ae2
work/ocean/INPUT/grid_spec.nc:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/modern/share/ocean/grids/mosaic/global.1deg/2020.05.19/grid_spec.nc
  hashes:
    binhash: 623f0c8a401432427a6c89564b8a0f62
    md5: b9adc1e552201aa3abc6efb72786ec93
work/ocean/INPUT/ocmip2_fice_monthly_om1p5_bc.nc:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/modern/unused/ocean/biogeochemistry/global.1deg/2020.05.19/ocmip2_fice_monthly_om1p5_bc.nc
  hashes:
    binhash: c88a9d880a8fdf81cc298afac6257c60
    md5: c0ed75eef44962dbe6fc9f61dbd228a9
work/ocean/INPUT/ocmip2_press_monthly_om1p5_bc.nc:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/modern/share/ocean/biogeochemistry/global.1deg/2020.05.19/ocmip2_press_monthly_om1p5_bc.nc
  hashes:
    binhash: 1f3621ba5a5e80fd346a52717efa5fff
    md5: 2e71cbb78c052e06e3df20f862928da2
work/ocean/INPUT/ocmip2_xkw_monthly_om1p5_bc.nc:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/modern/unused/ocean/biogeochemistry/global.1deg/2020.05.19/ocmip2_xkw_monthly_om1p5_bc.nc
  hashes:
    binhash: 09bac4f0f0da3edf1a7eb0ea9a262fab
    md5: 348a035bed83e280bb0a1de0066947fc
work/ocean/INPUT/roughness_amp.nc:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/modern/share/ocean/tides/global.1deg/2020.05.19/roughness_amp.nc
  hashes:
    binhash: 75d84af9e09b02d00f7be29eef7a5dbc
    md5: 185dadeb53da2de75b47c53fd7085f89
work/ocean/INPUT/ssw_atten_depth.nc:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/modern/share/ocean/shortwave_penetration/global.1deg/2020.05.19/ssw_atten_depth.nc
  hashes:
    binhash: fd668293ec6ede1f82667f0fa449138d
    md5: 3e88b51db135788aa4348d58cbeabfad
work/ocean/INPUT/tideamp.nc:
  fullpath: /g/data/vk83/experiments/inputs/access-esm1p5/modern/share/ocean/tides/global.1deg/2020.05.19/tideamp.nc
  hashes:
    binhash: fe958e4c8e68b35c7e3f4becbd8b337a
    md5: b2840af757d9b7b40207f33f1fc84c5c
